# ===========================================================================
# Example Docker Compose file
# ===========================================================================
#
# Purpose:
# --------
#
# This file is an example Docker Compose configuration for self hosting
# ROMS Finance on your local machine or on a cloud VPS.
#
# The configuration below is a "standard" setup that works out of the box,
# but if you're running this outside of a local network, it is recommended
# to set the environment variables for extra security.
#
# Setup:
# ------
#
# To run this, you should read the setup guide:
#
# https://github.com/RubenOussoren/roms-finance/blob/main/docs/hosting/docker.md
#
# Troubleshooting:
# ----------------
#
# If you run into problems, you should open a Discussion here:
#
# https://github.com/RubenOussoren/roms-finance/discussions
#

x-db-env: &db_env
  POSTGRES_USER: ${POSTGRES_USER:-roms_user}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-roms_password}
  POSTGRES_DB: ${POSTGRES_DB:-roms_production}

x-rails-env: &rails_env
  <<: *db_env
  SECRET_KEY_BASE: "${SECRET_KEY_BASE:?SECRET_KEY_BASE is required - generate with openssl rand -hex 64}"
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  DB_HOST: db
  DB_PORT: 5432
  REDIS_URL: redis://redis:6379/1
  CACHE_REDIS_URL: redis://redis:6379/2
  SIDEKIQ_WEB_USERNAME: ${SIDEKIQ_WEB_USERNAME:-roms}
  SIDEKIQ_WEB_PASSWORD: ${SIDEKIQ_WEB_PASSWORD:-roms}
# Optional: Synth API key for stock prices and exchange rates. You can also set this in Settings > Self-Hosting after login.
# SYNTH_API_KEY: ${SYNTH_API_KEY}
# NOTE: enabling OpenAI will incur costs when you use AI-related features in the app (chat, rules).  Make sure you have set appropriate spend limits on your account before adding this.
  OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
# Plaid — bank account connectivity (US & EU). Get credentials at https://dashboard.plaid.com
# PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
# PLAID_SECRET: ${PLAID_SECRET}
# PLAID_ENV: ${PLAID_ENV:-production}
# PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
# Plaid EU — separate credentials for European institutions
# PLAID_EU_CLIENT_ID: ${PLAID_EU_CLIENT_ID}
# PLAID_EU_SECRET: ${PLAID_EU_SECRET}
# SnapTrade — brokerage connectivity (Canada). Get credentials at https://snaptrade.com
# SNAPTRADE_CLIENT_ID: ${SNAPTRADE_CLIENT_ID}
# SNAPTRADE_CONSUMER_KEY: ${SNAPTRADE_CONSUMER_KEY}

services:
  web:
    image: ghcr.io/rubenoussoren/roms-finance:latest
    volumes:
      - app-storage:/rails/storage
    ports:
      - 3000:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      <<: *rails_env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - roms_net

  worker:
    image: ghcr.io/rubenoussoren/roms-finance:latest
    command: bundle exec sidekiq
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      <<: *rails_env
    networks:
      - roms_net

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      <<: *db_env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - roms_net

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - roms_net

volumes:
  app-storage:
  postgres-data:
  redis-data:

networks:
  roms_net:
    driver: bridge
